name: CI on Release
on:
  release:
    types: [created]
permissions:
    contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Tag Name
        run: echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Build
        run: ./build.sh ${{ github.event.release.tag_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            build/autotweak-${{ github.event.release.tag_name }}.tgz
            build/autotweak.plg
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         